"""Add validation run configuration fields

Revision ID: 118b96c3e5fe
Revises: 9c8951b27cb2
Create Date: 2025-05-26 19:56:59.944824

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "118b96c3e5fe"
down_revision: Union[str, None] = "9c8951b27cb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "validation_runs", sa.Column("auth_method", sa.String(), nullable=True)
    )
    op.add_column(
        "validation_runs", sa.Column("auth_config", sa.JSON(), nullable=True)
    )
    op.add_column(
        "validation_runs",
        sa.Column("test_strategies", sa.JSON(), nullable=True),
    )
    op.add_column(
        "validation_runs",
        sa.Column("max_examples", sa.Integer(), nullable=True),
    )
    op.add_column(
        "validation_runs", sa.Column("timeout", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validation_runs", "timeout")
    op.drop_column("validation_runs", "max_examples")
    op.drop_column("validation_runs", "test_strategies")
    op.drop_column("validation_runs", "auth_config")
    op.drop_column("validation_runs", "auth_method")
    # ### end Alembic commands ###
