"""add_contract_validations_table

Revision ID: ddaf96f289c2
Revises: 87ef3dd353b2
Create Date: 2025-05-29 13:48:28.740026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddaf96f289c2'
down_revision: Union[str, None] = '87ef3dd353b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_specification_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('provider_url', sa.String(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('mock_configuration_id', sa.Integer(), nullable=True),
    sa.Column('contract_health_status', sa.String(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('producer_validation_results', sa.JSON(), nullable=True),
    sa.Column('mock_alignment_results', sa.JSON(), nullable=True),
    sa.Column('validation_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_specification_id'], ['api_specifications.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['mock_configuration_id'], ['mock_configurations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_validations_id'), 'contract_validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_validations_id'), table_name='contract_validations')
    op.drop_table('contract_validations')
    # ### end Alembic commands ###
